### ISSUE TITLE
[7] Assertion failed: tensors.at(output.name()).is_tensor()

### ISSUE THREAD

**Issue by rahul411** [onnx/onnx-tensorrt#383]
I have toy onnx model which I am trying to convert to TensorRT, but I get the following error:
`ERROR: ModelImporter.cpp:316 In function importModel:
[7] Assertion failed: tensors.at(output.name()).is_tensor()
[E] failed to parse onnx file
[E] Engine could not be created
[E] Engine could not be created
`

Here is the the onnx model that I am trying to convert to TensorRT
```
import numpy as np
import onnx
from onnx import helper
from onnx import AttributeProto, TensorProto, GraphProto
from onnx.version_converter import convert_version
def main():
    Y = helper.make_tensor_value_info("Y", TensorProto.FLOAT, [1])
    tens = onnx.helper.make_tensor(
                name="tens_value",
                data_type=onnx.TensorProto.FLOAT,
                dims=(1,),
                vals=np.array([1]),
                raw=False,
            )

    node = onnx.helper.make_node("Constant", inputs=[], outputs=['Y'], value=tens)
    graph_def = helper.make_graph([node], "test-model", [], [Y]) # , inits)
    model_def = helper.make_model(graph_def, producer_name='onnx-example')
    onnx.checker.check_model(model_def)
    onnx.save(model_def, "models/out.onnx")
main()
```

Basically there is a constant node whose output is exposed as the model output. 
TensorRT is complaining about the output not been a tensor. 
TensorRT version: 5.1.5.0
Onnx version: 1.6.0

**Comment by JingyuQian** [comment]
There's a class called `TensorOrWeights` that stores tensor or weight values. I think in your case the parser takes your output as weights rather than tensor. 

I'm having a similar problem in which a value is regarded as tensor instead of weights, causing `assert is_weights()` failed. Don't know how to solve it, though.

**Comment by rmccorm4** [comment]
Hi, I believe this was fixed here: https://github.com/onnx/onnx-tensorrt/commit/ba53ee59da21af3096e38721327c74ec689f0f07

You might be able to add this fix in your own version, but it would probably be simpler to upgrade to TensorRT 7 and then build the OSS ONNX Parser from master branch

**Comment by JingyuQian** [comment]
Hi @rmccorm4,
Thanks for the reply. My problem still exists after I updated the latest master branch and did the build(I have TensorRT 7 installed). I'm not sure if #369 is related because the file that throws the error is `builtin_op_importers.cpp`.

I attach my model here and appreciate if you can take a moment to look at it: https://drive.google.com/open?id=1Ln9xXIN0A7jWzOHMVCzZnOegBryCgxZy

Steps to reproduce: 
1. Clone the latest onnx-tensorrt master branch
2. `mkdir build && cd build && cmake ..`
3. `make`
4. `./onnx2trt frozen_inference_subgraph.onnx -o test.trt`

**Comment by rmccorm4** [comment]
> I attach my model here and appreciate if you can take a moment to look at it: https://drive.google.com/open?id=1Ln9xXIN0A7jWzOHMVCzZnOegBryCgxZy

@daquexian FYI onnx-simplifier segfaults on this model from comment above

**Comment by rmccorm4** [comment]
Hi @JingyuQian,

Not sure I know enough to give you an educated answer on why this is failing at the moment, but based on these lines: https://github.com/onnx/onnx-tensorrt/blob/master/builtin_op_importers.cpp#L2454-L2455, I'd be curious to see what happens when you export your model with opset 10. Can you try that?

**Comment by JingyuQian** [comment]
> Hi @JingyuQian,
> 
> Not sure I know enough to give you an educated answer on why this is failing at the moment, but based on these lines: https://github.com/onnx/onnx-tensorrt/blob/master/builtin_op_importers.cpp#L2454-L2455, I'd be curious to see what happens when you export your model with opset 10. Can you try that?

Hi @rmccorm4,
The model fails to convert under opset 10. I only succeeded under opset 11. But the failure is due to `Pad` op rather than `Resize`.
The original TensorFlow .pb file can be found here: https://drive.google.com/file/d/1HXVBp4oqeejh2moVB6egbseueseTwxeP/view?usp=sharing
TensorFlow version: 1.14
tf2onnx version: 1.5.4/ee756a
onnx version: 1.6.0
conversion command: `python -m tf2onnx.convert --graphdef frozen_inference_subgraph.pb --output frozen_inference_subgraph.onnx --fold_const --opset 11 --inputs image_tensor:0 --outputs detection_boxes:0,detection_scores:0,detection_classes:0`

The following is error log:
```
2020-01-27 16:59:55,857 - INFO - Using tensorflow=1.14.0, onnx=1.6.0, tf2onnx=1.5.4/ee756a
2020-01-27 16:59:55,857 - INFO - Using opset <onnx, 10>
2020-01-27 16:59:58,528 - ERROR - Failed to convert node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad
OP=Pad
Name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad
Inputs:
	Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Slice:0=Slice, None, 1
	Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_Concat__1105:0=Concat, [2, 2], 6
Outpus:
	Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad:0=[-1, -1], 1
Traceback (most recent call last):
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 440, in version_1
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/graph.py", line 260, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_Concat__1105 must be Const
2020-01-27 16:59:58,558 - ERROR - Failed to convert node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_5
OP=Pad
Name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_5
Inputs:
	Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Slice_5:0=Slice, None, 1
	Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_5_Concat__1132:0=Concat, [1, 2], 6
Outpus:
	Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_5:0=[-1], 1
Traceback (most recent call last):
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 440, in version_1
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/graph.py", line 260, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_5_Concat__1132 must be Const
2020-01-27 16:59:58,566 - ERROR - Failed to convert node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_1
OP=Pad
Name=Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_1
Inputs:
	Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Slice_1:0=Slice, None, 1
	Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_1_Concat__1159:0=Concat, [1, 2], 6
Outpus:
	Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_1:0=[-1], 1
Traceback (most recent call last):
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 440, in version_1
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/graph.py", line 260, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_1_Concat__1159 must be Const
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/convert.py", line 145, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 577, in process_tf_graph
    raise exceptions[0]
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/onnx_opset/nn.py", line 440, in version_1
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/home/jingyu/.virtualenvs/cv/lib/python3.6/site-packages/tf2onnx/graph.py", line 260, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/stack_Concat__1105 must be Const
```

**Comment by JingyuQian** [comment]
I actually added ```std::cout << scales << std::end``` after https://github.com/onnx/onnx-tensorrt/blob/7dd4a7a85858c781336dc58f646214fb94ec5035/builtin_op_importers.cpp#L2454 to see what `scales` stores and I got is `(_, _, _, _)`. Not sure if this means anything.

**Comment by daquexian** [comment]
> > I attach my model here and appreciate if you can take a moment to look at it: https://drive.google.com/open?id=1Ln9xXIN0A7jWzOHMVCzZnOegBryCgxZy
> 
> @daquexian FYI onnx-simplifier segfaults on this model from comment above
> 
> ```
> root@c594e5f77284:/workspace# python3 -m onnxsim /mnt/frozen_inference_subgraph.onnx /mnt/frozen_inference_subgraph.simple.onnx 
> Simplifying...
> Segmentation fault (core dumped)
> ```

Thanks for your report!

I think it is a problem in ONNX Runtime. I have posted an issue in ONNX Runtime repo: https://github.com/microsoft/onnxruntime/issues/2924

**Comment by daquexian** [comment]
> > > I attach my model here and appreciate if you can take a moment to look at it: https://drive.google.com/open?id=1Ln9xXIN0A7jWzOHMVCzZnOegBryCgxZy
> > 
> > 
> > @daquexian FYI onnx-simplifier segfaults on this model from comment above
> > ```
> > root@c594e5f77284:/workspace# python3 -m onnxsim /mnt/frozen_inference_subgraph.onnx /mnt/frozen_inference_subgraph.simple.onnx 
> > Simplifying...
> > Segmentation fault (core dumped)
> > ```
> 
> Thanks for your report!
> 
> I think it is a problem in ONNX Runtime. I have posted an issue in ONNX Runtime repo: [microsoft/onnxruntime#2924](https://github.com/microsoft/onnxruntime/issues/2924)

It turns out some bug in onnx optimizer causes onnx simplifier crash. After upgrading onnx-simplifier to 0.2.4 and pass `--skip-optimization` the simplification finishes gracefully but the outputs before and after simplification are different. I have no clear idea of why it happens. Maybe the model has some special operators making the const-folding incorrect.

**Comment by JingyuQian** [comment]
@daquexian This model is an FPN model with non-max-suppression at the end (contains tf.while op). These 2 are my suspicions. Thanks for your info!

**Comment by mk-nvidia** [comment]
@JingyuQian Can you please re-upload the model? It is no longer available from the link you pasted earlier. Thanks!

**Comment by kevinch-nv** [comment]
Closing this due to inactivity. If you are still experiencing issues, feel free to open a new issue after upgrading to the newest TRT version.
