### ISSUE TITLE
ArgMax very slow

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx-tensorrt#669]
```python

class MI(nn.Module):

    """
    solves torch.max onnx time
    """

    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(3, 27, 1, 1)
        self.conv2 = nn.Conv2d(27, 45, 1, 1)

    def forward(self, x):
        size_in = torch.tensor(x.size())

        a = self.conv(x)
        a = self.conv2(a)

        out = F.interpolate(
            a,
            # size=(size_in[2], size_in[3]),
            size=(1080, 1920),
            # size=(512, 512),
            mode="bilinear",
            align_corners=True)
        x = torch.max(out, dim=1)[1]
        return x
        #return out


torch_model = MI()
x = torch.randn([1, 3, 1080, 1920])
# x = torch.randn([1, 32, 24, 24])
b = torch.randn([8, 4, 3, 3])
# torch_out = torch_model(x, b)

# Export the model
torch.onnx.export(torch_model,               # model being run
                  x,
                #   (x, b),
                  "a.onnx",
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=11,          # the ONNX version to export the model to
                  do_constant_folding=True,
                  verbose=True)
print('Done!')

```

Please test this model. You will found whole trt model latency comes to 50ms!!! While this is a simple model only contains 1 conv and 1 interplate.

The largest latency comes from torch.max -> ArgMax in ONNX. If I comment it out, the speed is 5ms.

Anyone knows why?

**Comment by kevinch-nv** [comment]
Thanks for the report. Looking into this.

**Comment by jinfagang** [comment]
@kevinch-nv Glad you pay attention to this issue, I am using TensorRT 7.2.3.

**Comment by tianbaochou** [comment]
any update?

**Comment by hlyf-xs** [comment]
Hello, have you solved the problem yet?

**Comment by rajeevsrao** [comment]
With TensorRT 8.x the latency is around 13.8 ms on a V100 GPU.

**Comment by kevinch-nv** [comment]
Performance gap addressed in later TRT release, closing this issue

**Comment by RunningLeon** [comment]
> Performance gap addressed in later TRT release, closing this issue

@kevinch-nv hi, same issue on 8.2.1.8. Could you post which TRT release the TopK is optimized and the statistics results if possible.

**Comment by serser** [comment]
Still too slow with TensorRT 8.4. Is it resolved in TensorRT 8.6?

**Comment by joihn** [comment]
@kevinch-nv 
in which  TRT release was it fixed exactly ? I can't find any info in the changelog 😢 

 I am still experiencing slow argmax on TensoRT 8.5 on nvidia Orin Nx embedded GPU.

Some folks can't easily update update TensoRT because they are working with embedded GPU, for which TRT version is defined by the OS version
